version: '3.3'

services:
  db:
    image: postgres:10.5
    restart: always
    container_name: db_bot
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tg_bot
      - POSTGRES_DB_HOST=127.0.0.53
    network_mode: "host"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    ports:
      - '5432:5432'
  api:
    build: .
    image: myapi
    restart: always
    container_name: api
    command: bash -c "uvicorn app:api --host 127.0.0.53"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tg_bot
    network_mode: "host"
    ports:
      - "8000:8000"
    depends_on:
      - db
  bot:
     image: api
     restart: always
     container_name: bot
     command: bash -c "python3 ./deploy.py"
     network_mode: "host"
     depends_on:
       - db
       - api
